version: "3.7"

services:
  nginx:
    build:
      context: ..
      dockerfile: ./docker/builds/Dockerfile
      target: nginx_prod
    networks:
      - default
      - traefik
    environment:
      TZ: 'Europe/Kiev'
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host:split.localhost'
      traefik.frontend.passHostHeader: 'true'
    restart: always
  php:
    build:
      context: ..
      dockerfile: ./docker/builds/Dockerfile
      target: fpm_prod
    environment:
      TZ: 'Europe/Kiev'
    restart: always
      
networks:
  traefik:
    external: true
